### ISSUE TITLE
possible to save canvas data with background image

### ISSUE THREAD

**Issue by matt-sd-watson** [andfanilo/streamlit-drawable-canvas#108]
Is it possible to save the canvas data along with the background image, either as a data frame or JSON? I have not yet been able to find an instance where the entirety of the canvas, including the background image, can be saved locally.

**Comment by andfanilo** [comment]
Hello,

Ah for now we're not passing the background image from the frontend back to Python because it made for even slower reruns on the Streamlit side :/ 
so I assumed that one could save the image on the server next to the state if needed, and use Pillow Image `paste` method to paste the drawing transparent PNG on the background image

**Comment by MichaelSeitz98** [comment]
Hi @matt-sd-watson and @andfanilo 

I am facing exactly the same problem just 2 years later. Did you @matt-sd-watson manage to solve the issue via the paste method? If so, how did you do it in detail? Would be much appreciated!

Thanks a lot!
Michael

**Comment by matt-sd-watson** [comment]
I moved away from streamlit in favor of Flask and Dash for my application. The `dcc.Graph` components works much better for my requirements.
