### ISSUE TITLE
Transform Mode does not update width and height

### ISSUE THREAD

**Issue by tm-topnet** [andfanilo/streamlit-drawable-canvas#65]
When i change the rectangle, it does not upgrade the width and height of dataframe, only the origins

**Comment by andfanilo** [comment]
Hello @tm-topnet 

Yes this is due to the nature of Fabric.js, who preserves the properties of objects by applying and storing a scale factor instead of recomputing a new height / width.

Find a similar discussion in https://github.com/andfanilo/streamlit-drawable-canvas/issues/36#issuecomment-766313289 where you should find the answer to your point.

Fanilo
